version: "2"
services:
  node:
    build: ./
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
      
  web:
    image: httpd:alpine
    volumes:
      - ./app:/usr/local/apache2/htdocs
    ports:
      - "4444:80"

